name: CI

on: [push, workflow_dispatch]

jobs:
  ci:
    name: CI
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Initialize Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ['12', '14', '16']
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up dependencies
        run: npm install
      - name: Build website
        run: npm run build
